services:
  db: # Nome do servi√ßo mais claro
    image: mysql:latest
    container_name: UC00605-Website-adopt-a-pet # Nome do contentor
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine  
    container_name: Redis
    ports:
      - "6379:6379"

  imposter:
    image: bbyars/mountebank:latest
    container_name: Imposter
    ports:
      - "2525:2525"
      - "4545:4545"
    volumes:
      - ./Mocks:/Mocks
    command: start --configfile /Mocks/imposters.json --allowInjection


volumes:
  mysql_data: